spring:
  cloud:
    function:
      definition: initializeTransaction;processTransaction
    stream:
      binders:
        solace-cloud:
          type: solace
          environment:
            solace:
              java:
                clientUsername: card-point-backend
                clientPassword: welcome99
                host: 'tcps://mr-connection-qii5syp4cda.messaging.solace.cloud:55443'
                msgVpn: cc-west
      bindings:
        initializeTransaction-in-0:
          destination: 'terminal/*/transaction/begin_tran'
          group: nonexclusive
        processTransaction-in-0:
          destination: 'process/${process.id}'

