spring:
  cloud:
    function:
      definition: initializeTransaction;processTransaction
    stream:
      binders:
        solace-cloud:
          type: solace
          environment:
            solace:
              java:
                clientUsername: solace-cloud-client
                clientPassword: aun9gei5rvmomkk368ollri8fe
                host: 'tcps://mr-connection-v251j35k86e.messaging.solace.cloud:55443'
                msgVpn: cardpointe-broker-uscentra
      bindings:
        initializeTransaction-in-0:
          destination: 'cardpointe/terminal/*/begin_tran'
          group: nonexclusive
        processTransaction-in-0:
          destination: 'process/${process.id}'

